### PR TITLE
Add CI for image building in PRs

### PR DESCRIPTION
**Pull request by kbdharun**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
It's better to avoid this since pushing a new image with the same tag will replace the stable one. I would recommend using ghcr for this purpose or just upload the resulting Containerfile as artifact.

**Comment by kbdharun** [comment]
> It's better to avoid this since pushing a new image with the same tag will replace the stable one. I would recommend using ghcr for this purpose or just upload the resulting Containerfile as artifact.

This CI workflow doesn't push to any registry, it just builds the image so that we can check if the additions or modifications succeed before merge. If necessary I will add the action to upload the artifact to action runs.

**Comment by mirkobrombin** [comment]
my fault D:

**Comment by kbdharun** [comment]
Completed in https://github.com/Vanilla-OS/dev-image/commit/7f3b8239a60ee780d3445a14652bdb23365cc49b

**Pull request closed without merging**
